# Copyright 2016, 2017 Peter Dimov
# Copyright (C) 2017, 2018 James E. King III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

# When copying this to a new library, be sure to update the name of the library
# in two places (once each at the top of install: and test_script:)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - develop
    - master

matrix:
  allow_failures:
    - MAYFAIL: true

environment:
  global:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    # see: http://www.boost.org/build/doc/html/bbv2/overview/invocation.html#bbv2.overview.invocation.properties
    # to use the default for a given environment, comment it out; recommend you build debug and release however..
    # on Windows it is important to exercise all the possibilities, especially shared vs static
    # B2_ADDRESS_MODEL: address-model=64,32
    # B2_LINK: link=shared,static
    # B2_THREADING: threading=multi,single
    B2_VARIANT: variant=release,debug
    CXXSTD: 03

  matrix:
    - FLAVOR: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64,32
    - FLAVOR: Visual Studio 2013
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: msvc-12.0
    - FLAVOR:  mingw32
      ARCH:    i686
      B2_ADDRESS_MODEL: address-model=32
      SCRIPT:  ci\mingw.bat
    - FLAVOR:  mingw64
      ARCH:    x86_64
      B2_ADDRESS_MODEL: address-model=64
      SCRIPT:  ci\mingw.bat
    - FLAVOR: cygwin (64-bit)
      ADDPATH: C:\cygwin64\bin;
      B2_ADDRESS_MODEL: address-model=64
      TOOLSET: gcc
      MAYFAIL: true
    - FLAVOR: cygwin (32-bit)
      ADDPATH: C:\cygwin\bin;
      B2_ADDRESS_MODEL: address-model=32
      TOOLSET: gcc
      MAYFAIL: true

install:
  - set SELF=program_options
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update -q --init tools/boostdep
  - git submodule update -q --init tools/build
  - git submodule update -q --init tools/inspect
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\%SELF%
  - python tools/boostdep/depinst/depinst.py --include example %SELF%
  - cmd /c bootstrap
  - b2 headers

build: off

test_script:
  - set SELF=program_options
  - PATH=%ADDPATH%%PATH%
  - IF DEFINED SCRIPT (call libs\%SELF%\%SCRIPT%) ELSE (b2 libs/%SELF% toolset=%TOOLSET% cxxstd=%CXXSTD% %CXXFLAGS% %DEFINES% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3)
